### ISSUE TITLE
Latest Nuget package is broken

### ISSUE THREAD

**Issue by jamiehowarth0** [BenjaminAbt/hcaptcha#1]
Hi there! I'm trying to implement this as an action filter in an ASP.NET MVC project (thus I can just add [HCaptchaValidator] to my actions - neat!)
However, your latest build appears to be broken, as it's not generating the Refit internal class (I've worked on Refit quite a bit myself, see screenshot):
![Screenshot of JetBrains dotPeek showing an "empty" Refit-generated namespace, excluding the PreserveAttribute that's always present](https://user-images.githubusercontent.com/322383/94490920-22e99400-01df-11eb-9055-89a6b21afd96.png)

**Comment by jamiehowarth0** [comment]
Found out why: you're using a constant for the path in the [Post] attribute.
This little internal method that checks the attribute is present, only checks for string values, not constants (I believe there's some debate over how we support this properly with semantic analysis).

![An image showing that only string literals are permitted in Refit attributes](https://user-images.githubusercontent.com/322383/94495052-a0fe6880-01e8-11eb-9a20-d51637f6d01d.png)

In the meantime, the fix will be to hardcode this in as a string I'm afraid. I'll do a manual edit & send it over and you should see it fix instantly.

**Comment by BenjaminAbt** [comment]
Thanks! Fixed with #4
