### ISSUE TITLE
"The Hostname field is required." Error

### ISSUE THREAD

**Issue by AlexanderGipp** [BenjaminAbt/hcaptcha#11]
If the captcha is **not solved** it returns a weird Error:
`The Hostname field is required.`

Do you know where this error is coming from and what causes it? 

I assume the error is set by the library because it only exists after the form post request has been sent

**captchaOptions**:
![image](https://user-images.githubusercontent.com/33844665/147355581-18e2db84-983f-4f5b-9fca-cb544be4235b.png)

**Comment by BenjaminAbt** [comment]
I cannot reproduce the error based on the repo sample.
![image](https://user-images.githubusercontent.com/6189336/147358722-660f39ea-48c0-4f77-bf9b-66de8e2cb20c.png)

`The Hostname field is required.` sound like an error in HttpClient, but the current hCaptcha settings are set by default.
https://github.com/BenjaminAbt/hcaptcha/blob/ee444e7ea3e5ace1467091039b5228145d2a1062/src/HCaptcha/HCaptchaOptions.cs#L39

So based on the info I would say the error is not coming from the lib.

**Comment by AlexanderGipp** [comment]
Thanks for getting back to me @BenjaminAbt, I will further investigate the issue and get back to you as soon as I know more about the problem.

This is the Project I am working on in case you want to take a look at it:
[VR Retreat](https://github.com/control-net/vr-retreat)

**Comment by AlexanderGipp** [comment]
@BenjaminAbt after adding the library directly to the project I figured out that setting `Hostname` in `HCaptchaVerifyResponse.cs` fixes the problem:

is there a way to somehow configure this (without adding the library directly to my solution)? 


```cs
    /// <summary>
    /// the hostname of the site where the captcha was solved
    /// </summary>
    /// <remarks>https://docs.hcaptcha.com/#server</remarks>
    [JsonPropertyName("hostname")]
    public string Hostname { get; set; } = null!;
    ```
    
    ```
    /// <summary>
    /// the hostname of the site where the captcha was solved
    /// </summary>
    /// <remarks>https://docs.hcaptcha.com/#server</remarks>
    [JsonPropertyName("hostname")]
    public string Hostname { get; set; } = "test.com";
    ```

**Comment by BenjaminAbt** [comment]
Maybe you have configured something wrong.
Your comment in

https://github.com/control-net/vr-retreat/blob/f42cc08516263b3aacd7e705853640a9fa488978/src/VrRetreat.WebApp/Controllers/AccountController.cs#L43

indicates the error is in the model state. Only one position is using this:

https://github.com/BenjaminAbt/hcaptcha/blob/ee444e7ea3e5ace1467091039b5228145d2a1062/src/HCaptcha.AspNetCore/HCaptchaModelBinder.cs#L43

you could debug there.

**Comment by BenjaminAbt** [comment]
> is there a way to somehow configure this (without adding the library directly to my solution)?

thats weird because the documentation of hcaptcha says its always filled.

**Comment by AlexanderGipp** [comment]
> Maybe you have configured something wrong. Your comment in
> 
> https://github.com/control-net/vr-retreat/blob/f42cc08516263b3aacd7e705853640a9fa488978/src/VrRetreat.WebApp/Controllers/AccountController.cs#L43
> 
> indicates the error is in the model state. Only one position is using this:
> 
> https://github.com/BenjaminAbt/hcaptcha/blob/ee444e7ea3e5ace1467091039b5228145d2a1062/src/HCaptcha.AspNetCore/HCaptchaModelBinder.cs#L43
> 
> you could debug there.

I just checked and this has nothing to do with the "The Hostname field is required." error

**Comment by AlexanderGipp** [comment]
> > is there a way to somehow configure this (without adding the library directly to my solution)?
> 
> thats weird because the documentation of hcaptcha says its always filled.

Do you think adding a default URL would be a good idea? I could open a merge request if you want.

**Comment by BenjaminAbt** [comment]
> I just checked and this has nothing to do with the "The Hostname field is required." error

You comment says its part of the ModelState.
Only one LOC of hcaptchanet is using / adding model state.

> Do you think adding a default URL would be a good idea? I could open a merge request if you want.

I would suggest to null this line to 

```
public string? Hostname { get; set; }
```

Can you verify this works for you?

**Comment by AlexanderGipp** [comment]
> > I just checked and this has nothing to do with the "The Hostname field is required." error
> 
> You comment says its part of the ModelState. Only one LOC of hcaptchanet is using / adding model state.
> 
> > Do you think adding a default URL would be a good idea? I could open a merge request if you want.
> 
> I would suggest to null this line to
> 
> ```
> public string? Hostname { get; set; }
> ```
> 
> Can you verify this works for you?
Making `Hostname nullable` fixed the issue, do you want me to create a merge request?

```cs
    /// <summary>
    /// the hostname of the site where the captcha was solved
    /// </summary>
    /// <remarks>https://docs.hcaptcha.com/#server</remarks>
    [JsonPropertyName("hostname")]
    public string? Hostname { get; set; } = null!;
    ```

**Comment by BenjaminAbt** [comment]
yes, feel free. thank you.

but it should be:
```cs
public string? Hostname { get; set; }
```
because
```cs
public string? Hostname { get; set; } = null!;
```

is not valid :-)

**Comment by AlexanderGipp** [comment]
Alright I opened a merge request, thanks for your help and Merry Christmas 😅

**Comment by BenjaminAbt** [comment]
Thank you, same to you!
