### ISSUE TITLE
Add option to configure HttpClientHandler

### ISSUE THREAD

**Issue by Matti-Koopa** [BenjaminAbt/hcaptcha#7]
This library should support named HttpClients. This allows the use of, for example, a proxy server.

As this library is using Refit, this would be done like so, to use the named client "Default":
```
clientBuilder.ConfigureHttpMessageHandlerBuilder(handlerBuilder => handlerBuilder.Name = "Default")
```
I tried to fork this and add it myself using another parameter for `AddHCaptcha`: https://github.com/Matti-Koopa/hcaptcha/blob/master/src/HCaptcha.AspNetCore/HCaptchaExtensions.cs so that you can do something like this:
```
services.AddHCaptcha(captchaSection, clientBuilder =>
    clientBuilder.ConfigureHttpMessageHandlerBuilder(handlerBuilder => handlerBuilder.Name = "Default"));
```

Sadly, I couldn't get this to work locally as Refit always complained that `IHCaptchaApi` "doesn't look like a Refit interface" (seems to be [this](https://github.com/reactiveui/refit/issues/318) issue).

Maybe you could get it to work somehow? An alternative would be to just get rid of the Refit dependency alltogether. It seems overkill for just a single endpoint anyway.

**Comment by BenjaminAbt** [comment]
Hi, thanks for your contribution!
I will update the lib to the latest Refit, which solves some issues like inheritance.
Will also add a better HttpClient implemenation based on the latest httpClientFactory docs of .NET

Thank you!

**Comment by BenjaminAbt** [comment]
I have updated the latest bits to .NET 6 and Refit 6, which supports source code generators and more.
Feel free to use Refit HttpClientFactory options or a custom HttpClientFactory (see readme) for your needs.
